name = "cognition-api"
main = "src/index.ts"
compatibility_date = "2026-02-05"

[vars]
APP_NAME = "Cognitive Readiness Check"
COOKIE_NAME = "cc_session"
COOKIE_MAX_AGE_SECONDS = "1209600" # 14 days
WEB_ORIGIN = "https://provecognition.site" 
EMAIL_FROM = "Cognition <no-reply@send.provecognition.site>"



[[d1_databases]]
binding = "DB"
database_name = "cognition_db"
database_id = "d5a56fc7-b949-4ff0-a4af-db13e672d243"
